// `billing checkout --plan <id>` handler (T-215, billing.checkout, billing:write, M — D-2/D-3,
// R-C/R-E). The money-path Stripe checkout ceremony: an M-class `direct` mutation (Seam-1) that
// runs the M y/N confirm (non-TTY without `--yes` → `confirmation_required`), then sends EXACTLY
// ONE `billing.checkout` request and returns the `{object:"checkout_session", url}` DTO verbatim —
// a Stripe-hosted URL a HUMAN opens (the CLI never opens a browser).
//
// R-C (NO PREFETCH — scope fidelity): a `billing:write` command exercises ONLY its own route's
// scope. The request body carries `email` ONLY when `--email` was given; when omitted, the member
// is ABSENT (not null) and the SERVER derives the checkout email from the authenticated account
// (§0.5 dependency). The handler NEVER calls `account.get` (or any op outside billing.checkout).
// Idempotency-Key is auto-generated by the client layer from the route row's `idempotency:"required"`
// (the `--idempotency-key` client override remains available) — the handler adds nothing.
//
// `--plan` is USER-SUPPLIED and UNINTERPRETED: the CLI never enumerates or validates plan names
// (the server owns the set; an invalid id → 400 `invalid_request`). No plan catalog lives here.
import { z } from "zod";
import type { CommandHandler } from "../types";

export const billingCheckoutArgs = z
  .object({
    plan: z.string().min(1).describe("Plan id (server-validated; see `agkit billing plans`)."),
    email: z
      .string()
      .min(1)
      .optional()
      .describe("Checkout email; when omitted, the server uses your account email on file."),
  })
  .strict();
export type BillingCheckoutInput = z.infer<typeof billingCheckoutArgs>;

/**
 * PURE static checkout preview (R-C copy — no post-confirm lookup, derived only from the parsed
 * input). Line 2 states the email source: the on-file default when `--email` is absent, or the
 * literal address when supplied (flows through the ceremony's redact/displaySafe render).
 */
export function billingCheckoutPreview(input: unknown): { title: string; lines: readonly string[] } {
  const i = (input ?? {}) as { plan?: string; email?: string };
  const plan = typeof i.plan === "string" ? i.plan : "?";
  const emailLine =
    i.email !== undefined
      ? `email: ${i.email}`
      : "email: uses your account email on file (override with --email)";
  return {
    title: "billing checkout",
    lines: [
      `creates a Stripe checkout session for plan '${plan}' (account is charged only after you complete checkout in the browser)`,
      emailLine,
      "returns a URL — the CLI never opens a browser",
    ],
  };
}

export const billingCheckout: CommandHandler<BillingCheckoutInput> = async (ctx, input) => {
  // Seam-1.6: fail closed if the dispatch hook was bypassed (the M-direct ceremony must have run).
  if (ctx.ceremony?.kind !== "proceed") {
    throw new Error("agkit: internal — the billing checkout ceremony pass is missing (dispatch hook did not run?)");
  }
  // R-C: the `email` member is ABSENT (never null/undefined-valued) when `--email` was not given;
  // the server derives it from the authenticated account. `params` (minus path segments) is the
  // POST JSON body — this route has none, so it IS the body.
  const params = input.email !== undefined ? { plan: input.plan, email: input.email } : { plan: input.plan };
  const data = await ctx.client.request({ operationId: "billing.checkout", params });
  return { data, warnings: ["open this URL in your browser to complete checkout"] };
};
