// `billing portal` handler (T-215, billing.portal, billing:write, M — D-2, R-C/R-E). The money-path
// Stripe billing-portal ceremony: an M-class `direct` mutation (Seam-1) that runs the M y/N confirm
// (non-TTY without `--yes` → `confirmation_required`), then sends EXACTLY ONE `billing.portal`
// request with an EMPTY body and returns the `{object:"portal_session", url}` DTO verbatim — a
// Stripe-hosted URL a HUMAN opens.
//
// The customerId is TOKEN-DERIVED server-side; the CLI never sends one. Idempotency-Key is
// auto-generated by the client layer from the route row's `idempotency:"required"`.
import { z } from "zod";
import type { CommandHandler } from "../types";

export const billingPortalArgs = z.object({}).strict();
export type BillingPortalInput = z.infer<typeof billingPortalArgs>;

/** PURE static portal preview — no plan / email lines; opens nothing, returns a URL. */
export function billingPortalPreview(_input: unknown): { title: string; lines: readonly string[] } {
  return {
    title: "billing portal",
    lines: ["opens nothing — returns your Stripe billing-portal URL for a human to open in the browser"],
  };
}

export const billingPortal: CommandHandler<BillingPortalInput> = async (ctx) => {
  if (ctx.ceremony?.kind !== "proceed") {
    throw new Error("agkit: internal — the billing portal ceremony pass is missing (dispatch hook did not run?)");
  }
  // Empty body: the customerId is token-derived server-side.
  const data = await ctx.client.request({ operationId: "billing.portal", params: {} });
  return { data, warnings: ["open this URL in your browser to manage billing"] };
};
