/* AUTO-GENERATED by scripts/gen-contract-types.ts from contract/management/v1.2.0 — DO NOT EDIT.
 * Regenerate: pnpm --filter @agentkit-cloud/shared gen:contract-types
 * TYPE-ONLY: interfaces + the operation-keyed Operations map. Zero runtime values (erases at
 * build) — safe for the tsup-bundled CLI. The JSON bundle stays the runtime source of truth. */
/* eslint-disable */

export type ObjectType = string;
export type Timestamp = string;
export type Etag = string;
export type MoneyString = string | null;
export type CounterString = string | null;
export type Cursor = string;
export type MaskedSecret = string;
export type IssuerCreateRequest = {
  [k: string]: unknown;
} & {
  kind: "apple" | "firebase" | "custom_jwks" | "custom_public_key";
  issuer?: string;
  jwks_uri?: string;
  audience?: string;
  firebase_project_id?: string;
  public_key?: string;
  algorithm?: "RS256" | "ES256" | "EdDSA";
};
export type KillSwitchSetRequest =
  | {
      active: true;
      reason: string;
      confirm: string;
    }
  | {
      active: false;
    };
export type Project = ResourceBase & {
  name?: string;
  slug?: string;
  [k: string]: unknown;
};
export type ModelRoute = ResourceBase & {
  tier?: string;
  model?: string;
  [k: string]: unknown;
};
export type PublishableKey = ResourceBase & {
  masked_secret?: MaskedSecret;
  [k: string]: unknown;
};
export type ManagementToken = ResourceBase & {
  masked_secret?: MaskedSecret;
  scopes?: string[];
  project_ids?: string[];
  [k: string]: unknown;
};
export type ProviderCredential = ResourceBase & {
  provider?: string;
  masked_secret?: MaskedSecret;
  endpoint_url?: string | null;
  auth_style?: "authorization_bearer" | "api_key_header";
  header_name?: string;
  extra_headers?: {
    [k: string]: string;
  };
  config_status?: "valid" | "rejected";
  [k: string]: unknown;
};
export type Quota = ResourceBase & {
  monthly_token_cap?: CounterString;
  monthly_spend_cap_usd?: MoneyString;
  tokens_used?: CounterString;
  spend_usd?: MoneyString;
  max_requests_per_second_per_user?: number;
  max_turns_per_day_per_user?: number | null;
  max_monthly_spend_per_user_usd?: MoneyString;
  monthly_spend_alert_threshold_usd?: MoneyString;
  [k: string]: unknown;
};
export type PublishableKeyMintResponse = ResourceBase & {
  key: string | null;
  secret_unavailable: boolean;
  recovery_hint: string | null;
  masked_secret?: MaskedSecret;
  [k: string]: unknown;
};
export type ManagementTokenCreateRequest = {
  [k: string]: unknown;
} & {
  name: string;
  /**
   * @minItems 1
   */
  scopes?: [string, ...string[]];
  binding: "account" | "projects";
  /**
   * @minItems 1
   */
  project_ids?: [string, ...string[]];
  expires_at: string;
};
export type ManagementTokenMintResponse = ResourceBase & {
  token: string | null;
  secret_unavailable: boolean;
  recovery_hint: string | null;
  masked_secret?: MaskedSecret;
  scopes?: string[];
  project_ids?: string[];
  [k: string]: unknown;
};
export type TrustedIssuer = ResourceBase & {
  kind?: "apple" | "firebase" | "custom_jwks" | "custom_public_key";
  issuer?: string;
  jwks_uri?: string;
  audience?: string;
  firebase_project_id?: string;
  algorithm?: "RS256" | "ES256" | "EdDSA";
  public_key?: string;
  [k: string]: unknown;
};
export type AttestedKey = ResourceBase & {
  key_id?: string;
  external_user_id_hash?: string;
  environment?: "development" | "production";
  counter?: number;
  last_asserted_at?: string | null;
  revoked_at?: string | null;
  [k: string]: unknown;
};
export type OauthGrant = ResourceBase & {
  client_display_name?: string;
  scopes?: string[];
  binding?: "account" | "projects";
  project_ids?: string[];
  absolute_expires_at?: string;
  revoked_at?: string | null;
  live_token_counts?: {
    access: number;
    ci: number;
    legacy: number;
  };
  tokens?: {
    id: string;
    token_class: string;
    created_at: string;
    expires_at: string | null;
    revoked_at: string | null;
    last_used_at: string | null;
  }[];
  already_revoked?: true;
  [k: string]: unknown;
};
export type OauthGrantPage = ManagementList & {
  data?: OauthGrant[];
  [k: string]: unknown;
};

export interface ResourceBase {
  object: ObjectType;
  id: string;
  created_at: Timestamp;
  updated_at?: Timestamp;
  etag: Etag;
  [k: string]: unknown;
}
export interface PlanCreateRequest {
  note?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  changes:
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
        }
      ];
  expires_in_seconds?: number;
}
export interface PlanApplyRequest {
  confirm?: string | null;
}
export interface ProjectCreateRequest {
  name: string;
  slug?: string;
}
export interface ProjectUpdateRequest {
  name?: string;
  app_attest_app_id?: string | null;
  app_attest_environment?: "development" | "production";
}
export interface ModelRouteCreateRequest {
  tier: string;
  model: string;
  provider: string;
  execution_target: string;
  fallback_execution_target: string | null;
  attestation: string;
  enabled: boolean;
  default: boolean;
}
export interface ModelRouteUpdateRequest {
  provider?: string;
  model?: string;
  execution_target?: string;
  fallback_execution_target?: string | null;
  attestation?: string;
  enabled?: boolean;
  default?: boolean;
}
export interface AgentProfileCreateRequest {
  slug: string;
  display_name: string;
  static_system_prompt: string;
  allowed_tiers: string[];
  max_input_tokens: number;
  max_output_tokens: number;
  enabled: boolean;
  safety_settings: {} | null;
  thinking_config: {} | null;
}
export interface AgentProfileUpdateRequest {
  display_name?: string;
  static_system_prompt?: string;
  allowed_tiers?: string[];
  max_input_tokens?: number;
  max_output_tokens?: number;
  enabled?: boolean;
  safety_settings?: {} | null;
  thinking_config?: {} | null;
}
export interface ToolCreateRequest {
  tool_name: string;
  description: string;
  parameter_schema: {};
}
export interface ToolUpdateRequest {
  description?: string;
  parameter_schema?: {};
  enabled?: boolean;
}
export interface ProviderCredentialCreateRequest {
  provider: string;
  api_key: string;
  endpoint_url?: string;
  auth_style?: "authorization_bearer" | "api_key_header";
  header_name?: string;
  extra_headers?: {
    [k: string]: string;
  };
}
export interface IssuerUpdateRequest {
  issuer?: string;
  jwks_uri?: string;
  audience?: string;
  firebase_project_id?: string;
  public_key?: string;
  algorithm?: "RS256" | "ES256" | "EdDSA";
}
export interface MediaRouteUpsertRequest {
  provider: string;
  model: string;
  enabled?: boolean;
  config?: {};
}
export interface MediaRouteToggleRequest {
  enabled: boolean;
}
export interface VoiceIdentityUpsertRequest {
  resource_id: string;
  confirm: string;
  enabled?: boolean;
}
export interface VoiceIdentityToggleRequest {
  enabled: boolean;
  confirm: string;
}
export interface RevenuecatUpsertRequest {
  api_key: string;
  confirm: string;
}
export interface QuotasUpsertRequest {
  max_requests_per_second_per_user: number;
  max_turns_per_day_per_user: number | null;
  monthly_token_cap: CounterString;
  monthly_spend_cap_usd: MoneyString;
  max_monthly_spend_per_user_usd: MoneyString;
  monthly_spend_alert_threshold_usd: MoneyString;
}
export interface MediaQuotasUpsertRequest {
  max_image_generations_per_day: number | null;
  max_audio_seconds_per_day: number | null;
  max_video_generations_per_day: number | null;
  max_dubbing_jobs_per_day: number | null;
  monthly_media_budget_usd: MoneyString;
  media_budget_alert_threshold_usd: MoneyString;
}
export interface MediaQuotas {
  object: "media_quotas";
  max_image_generations_per_day: number | null;
  max_audio_seconds_per_day: number | null;
  max_video_generations_per_day: number | null;
  max_dubbing_jobs_per_day: number | null;
  monthly_media_budget_usd: MoneyString;
  media_budget_alert_threshold_usd: MoneyString;
  created_at: Timestamp;
}
export interface PublishableKeyCreateRequest {
  name: string;
}
export interface RevokeConfirmRequest {
  confirm: string;
}
export interface ManagementList {
  object: "list";
  data: ResourceBase[];
  has_more: boolean;
  next_cursor?: Cursor;
  [k: string]: unknown;
}
export interface ModelRouteDefault {
  route: ModelRouteCreateRequest1;
  requires_credential: string;
  note?: string;
}
export interface ModelRouteCreateRequest1 {
  tier: string;
  model: string;
  provider: string;
  execution_target: string;
  fallback_execution_target: string | null;
  attestation: string;
  enabled: boolean;
  default: boolean;
}
export interface ModelRouteDefaultsResponse {
  object: "model_route_defaults";
  catalog_version: string;
  /**
   * @maxItems 10
   */
  defaults:
    | []
    | [ModelRouteDefault]
    | [ModelRouteDefault, ModelRouteDefault]
    | [ModelRouteDefault, ModelRouteDefault, ModelRouteDefault]
    | [ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault]
    | [ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault]
    | [ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault, ModelRouteDefault]
    | [
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault
      ]
    | [
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault
      ]
    | [
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault
      ]
    | [
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault,
        ModelRouteDefault
      ];
}
export interface CheckoutCreateRequest {
  plan: string;
  email?: string;
  accountId?: string;
}
export interface ManagementProblem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  code: string;
  request_id: string;
  retry: "none" | "refresh_auth" | "retry_with_backoff";
  required_scopes?: string[];
  drifted?: unknown[];
  current_etag?: Etag;
  errors?: {
    pointer: string;
    code: string;
    message: string;
  }[];
  retry_after?: number;
  supported_major?: string;
  limit?: number;
  current?: number;
  reason?: string;
  secret_unavailable?: boolean;
  hint?: string;
  [k: string]: unknown;
}
export interface ManagementPlan {
  object: "plan";
  id: string;
  status: "open" | "applied" | "discarded" | "expired";
  /**
   * @maxItems 20
   */
  changes:
    | []
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ]
    | [
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        },
        {
          action: "create" | "update" | "delete" | "invoke";
          resource: string;
          path: string;
          body?: unknown;
          [k: string]: unknown;
        }
      ];
  diff?: {
    op: string;
    resource: string;
    path: string;
    before?: unknown;
    after?: unknown;
    [k: string]: unknown;
  }[];
  preconditions?: (
    | {
        etag: unknown;
      }
    | {
        absent: unknown;
      }
  )[];
  state_hash: string;
  confirm_string?: string | null;
  danger: "SR" | "M" | "D" | "PR";
  gating: "free" | "direct" | "direct_confirm" | "plan_required";
  created_by?: string;
  expires_at?: Timestamp;
  created_at: Timestamp;
  results?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

/**
 * Every management operation_id paired with its request/response DTO (A17/A34). Unmapped
 * halves are `unknown`. The typed client seam narrows to `Operations[K]["response"]`.
 */
export interface Operations {
  "discovery.get": { request: unknown; response: unknown };
  "self.get": { request: unknown; response: unknown };
  "whoami.get": { request: unknown; response: unknown };
  "oauth.device_authorization": { request: unknown; response: unknown };
  "oauth.token": { request: unknown; response: unknown };
  "oauth.revocation": { request: unknown; response: unknown };
  "oauth.meta.as": { request: unknown; response: unknown };
  "oauth.meta.prm": { request: unknown; response: unknown };
  "oauth.authorize": { request: unknown; response: unknown };
  "account.get": { request: unknown; response: unknown };
  "account.usage": { request: unknown; response: unknown };
  "billing.get": { request: unknown; response: unknown };
  "billing.plans": { request: unknown; response: unknown };
  "billing.checkout": { request: CheckoutCreateRequest; response: unknown };
  "billing.portal": { request: unknown; response: unknown };
  "member.list": { request: unknown; response: unknown };
  "member.update": { request: unknown; response: unknown };
  "member.remove": { request: unknown; response: unknown };
  "invitation.list": { request: unknown; response: unknown };
  "invitation.create": { request: unknown; response: unknown };
  "invitation.revoke": { request: unknown; response: unknown };
  "audit.list": { request: unknown; response: unknown };
  "project.list": { request: unknown; response: unknown };
  "project.create": { request: ProjectCreateRequest; response: Project };
  "project.get": { request: unknown; response: Project };
  "project.update": { request: ProjectUpdateRequest; response: Project };
  "project.archive": { request: unknown; response: unknown };
  "project.summary": { request: unknown; response: unknown };
  "publishable_key.list": { request: unknown; response: unknown };
  "publishable_key.create": { request: PublishableKeyCreateRequest; response: PublishableKeyMintResponse };
  "publishable_key.get": { request: unknown; response: PublishableKey };
  "publishable_key.revoke": { request: RevokeConfirmRequest; response: unknown };
  "management_token.list": { request: unknown; response: unknown };
  "management_token.create": { request: ManagementTokenCreateRequest; response: ManagementTokenMintResponse };
  "management_token.get": { request: unknown; response: ManagementToken };
  "management_token.revoke": { request: RevokeConfirmRequest; response: unknown };
  "issuer.list": { request: unknown; response: unknown };
  "issuer.create": { request: unknown; response: unknown };
  "issuer.get": { request: unknown; response: TrustedIssuer };
  "issuer.update": { request: unknown; response: unknown };
  "issuer.delete": { request: unknown; response: unknown };
  "credential.list": { request: unknown; response: unknown };
  "credential.create": { request: ProviderCredentialCreateRequest; response: ProviderCredential };
  "credential.get": { request: unknown; response: ProviderCredential };
  "credential.rotate": { request: unknown; response: unknown };
  "credential.revoke": { request: RevokeConfirmRequest; response: unknown };
  "attested_key.list": { request: unknown; response: unknown };
  "attested_key.revoke": { request: RevokeConfirmRequest; response: unknown };
  "model_route.list": { request: unknown; response: unknown };
  "model_route.create": { request: unknown; response: unknown };
  "model_route.defaults": { request: unknown; response: ModelRouteDefaultsResponse };
  "model_route.get": { request: unknown; response: ModelRoute };
  "model_route.update": { request: unknown; response: unknown };
  "model_route.delete": { request: unknown; response: unknown };
  "profile.list": { request: unknown; response: unknown };
  "profile.create": { request: unknown; response: unknown };
  "profile.get": { request: unknown; response: unknown };
  "profile.update": { request: unknown; response: unknown };
  "profile.delete": { request: unknown; response: unknown };
  "tool.list": { request: unknown; response: unknown };
  "tool.create": { request: unknown; response: unknown };
  "tool.get": { request: unknown; response: unknown };
  "tool.update": { request: unknown; response: unknown };
  "tool.delete": { request: unknown; response: unknown };
  "profile.sync": { request: unknown; response: unknown };
  "media_route.list": { request: unknown; response: unknown };
  "media_route.get": { request: unknown; response: unknown };
  "media_route.upsert": { request: unknown; response: unknown };
  "media_route.toggle": { request: unknown; response: unknown };
  "identity.list": { request: unknown; response: unknown };
  "identity.get": { request: unknown; response: unknown };
  "identity.upsert": { request: VoiceIdentityUpsertRequest; response: unknown };
  "identity.toggle": { request: VoiceIdentityToggleRequest; response: unknown };
  "identity.revalidate": { request: unknown; response: unknown };
  "identity.delete": { request: unknown; response: unknown };
  "revenuecat.get": { request: unknown; response: unknown };
  "revenuecat.upsert": { request: RevenuecatUpsertRequest; response: unknown };
  "revenuecat.disable": { request: unknown; response: unknown };
  "quotas.get": { request: unknown; response: Quota };
  "quotas.upsert": { request: unknown; response: unknown };
  "media_quotas.get": { request: unknown; response: MediaQuotas };
  "media_quotas.upsert": { request: unknown; response: unknown };
  "kill_switch.get": { request: unknown; response: unknown };
  "kill_switch.set": { request: KillSwitchSetRequest; response: unknown };
  "usage.series": { request: unknown; response: unknown };
  "usage.requests": { request: unknown; response: unknown };
  "usage.top_users": { request: unknown; response: unknown };
  "end_user.list": { request: unknown; response: unknown };
  "end_user.get": { request: unknown; response: unknown };
  "media_usage.summary": { request: unknown; response: unknown };
  "media_usage.costs": { request: unknown; response: unknown };
  "media_usage.requests": { request: unknown; response: unknown };
  "media_job.list": { request: unknown; response: unknown };
  "media_job.get": { request: unknown; response: unknown };
  "plan.create": { request: PlanCreateRequest; response: ManagementPlan };
  "plan.list": { request: unknown; response: unknown };
  "plan.get": { request: unknown; response: ManagementPlan };
  "plan.apply": { request: PlanApplyRequest; response: ManagementPlan };
  "plan.discard": { request: unknown; response: unknown };
  "admin.account.list": { request: unknown; response: unknown };
  "admin.account.update": { request: unknown; response: unknown };
  "admin.user.find": { request: unknown; response: unknown };
  "admin.user.reset_totp": { request: unknown; response: unknown };
  "admin.user.clear_lockout": { request: unknown; response: unknown };
  "admin.kill_switch.get": { request: unknown; response: unknown };
  "admin.kill_switch.set": { request: unknown; response: unknown };
  "knowledge.bank.list": { request: unknown; response: unknown };
  "knowledge.bank.create": { request: unknown; response: unknown };
  "knowledge.bank.get": { request: unknown; response: unknown };
  "knowledge.bank.update": { request: unknown; response: unknown };
  "knowledge.bank.delete": { request: unknown; response: unknown };
  "knowledge.document.list": { request: unknown; response: unknown };
  "knowledge.document.upload": { request: unknown; response: unknown };
  "knowledge.document.get": { request: unknown; response: unknown };
  "knowledge.document.delete": { request: unknown; response: unknown };
  "knowledge.document.purge": { request: unknown; response: unknown };
  "knowledge.index.list": { request: unknown; response: unknown };
  "knowledge.index.build": { request: unknown; response: unknown };
  "knowledge.index.activate": { request: unknown; response: unknown };
  "knowledge.binding.list": { request: unknown; response: unknown };
  "knowledge.binding.create": { request: unknown; response: unknown };
  "knowledge.binding.get": { request: unknown; response: unknown };
  "knowledge.binding.update": { request: unknown; response: unknown };
  "knowledge.binding.delete": { request: unknown; response: unknown };
  "knowledge.embedding_route.get": { request: unknown; response: unknown };
  "knowledge.embedding_route.set": { request: unknown; response: unknown };
  "knowledge.quota.get": { request: unknown; response: unknown };
  "knowledge.quota.set": { request: unknown; response: unknown };
  "knowledge.usage.get": { request: unknown; response: unknown };
  "knowledge.retrieval_log.list": { request: unknown; response: unknown };
  "knowledge.ingest_job.list": { request: unknown; response: unknown };
  "knowledge.ingest_report.get": { request: unknown; response: unknown };
  "knowledge.storage_snapshot.list": { request: unknown; response: unknown };
  "profile.sync.legacy": { request: unknown; response: unknown };
  "billing.checkout.legacy": { request: unknown; response: unknown };
  "billing.portal.legacy": { request: unknown; response: unknown };
  "oauth.grant.list": { request: unknown; response: OauthGrantPage };
  "oauth.grant.get": { request: unknown; response: OauthGrant };
  "oauth.grant.revoke": { request: RevokeConfirmRequest; response: unknown };
  "oauth.meta.as.root": { request: unknown; response: unknown };
  "oauth.meta.prm.root": { request: unknown; response: unknown };
}

/** All management operation_ids as a string-literal union. */
export type ManagementOperationId = keyof Operations;
